### ISSUE TITLE
Add a lightbox functionality for emphasizing an image/plot

### ISSUE THREAD

**Issue by nstrayer** [nstrayer/tuftesque2#4]
Based on this tweet: 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Great work ! Testing it right now and I think i&#39;m gonna use it soon for a report. What do you think about implementing something similar to lightbox and gallery from <a href="https://t.co/Gzes6XmN1t">https://t.co/Gzes6XmN1t</a> ?</p>&mdash; Félix M. (@felix_mil_) <a href="https://twitter.com/felix_mil_/status/1121788187955752961?ref_src=twsrc%5Etfw">April 26, 2019</a></blockquote>

Adding this should be as simple as adding a hover event to an image that breaks it out of the block structure, transitions it to the middle of the screen and adds a psuedo element behind it to create the blurred/dimmed background.

**Comment by Felixmil** [comment]
I found this 'pure css' lightbox solution: https://codepen.io/gschier/pen/HCoqh.

It worked after adding the css and the html as text in the .Rmd. 
But when I tried to do it from code chunks directly I got no working results. This is what I tried:

Since this method needs two example of the same image with different classes :

```
```{r plot, echo=FALSE, fig.height = 2, fig.width=5} # This plot is visible in the report
tibble::tibble( x = rpois(200, 40) ) %>% 
  ggplot(aes(x = x)) + 
  geom_histogram(bins = 100)
``
```{r, ref.label='plot',class='lightbox', results='hide'} # This plot is the exact copy of the first chunk but has lightbox class
``
```
The problem is that I couldn't find a way to link the visible plot to the 'lightbox' one (output .html should contain `<a href="#plot">` on the visible plot)

Even though I realize this is not really viable in the end, this is all I could find for now without adding any JS dependencies.

**Comment by nstrayer** [comment]
Oh that's a good find! I made a few changes to it so it only requires a single image meaning it should be relatively easy to put it in as a simple class functionality: https://codepen.io/nstrayer/pen/wZNmGN?editors=1100 
The only difficulty is this requires the image/plot to be wrapped in a div, which we can certainly do. Another option would be to add a hidden background div that is always loaded on the page that gets activated when an image is clicked. It would require a tiny bit of vanilla javascript but that already exists for the mobile sidenotes. https://github.com/nstrayer/tuftesque2/blob/master/inst/tuftesque.html#L52-L69

Do you see this being used primarily for plots or for images in general?

**Comment by nstrayer** [comment]
In 810b17c4c970f6c5a60a0b53663640c7e0e80285 I added the ability to put `class='lightbox'` in the code chunk that makes a plot. When you click on a plot made this way it will display in a lightbox. 

_normal_
![image](https://user-images.githubusercontent.com/6764693/56843772-71b53080-686b-11e9-999c-2ee399c32dca.png)

_after click_
![image](https://user-images.githubusercontent.com/6764693/56843777-80034c80-686b-11e9-814a-77a3792d92ac.png)

Does this satisfy the use case you were thinking of? The one thing it is lacking currently is the ability to have text etc.

**Comment by Felixmil** [comment]
wow that was quick ! I got the css part of your commit but not the html/js part. Anyway it's the first time I'm participating in a package development and I'm learning a lot thanks to your explanations, thank you !

Regarding the feature: it is absolutely what I was thinking about. However, I think this would at its maximum greatness if it worked on sidenotes plots! They tend to be a bit small and not very readable, I think the real value is here 🎯 . So, I'll work on that. 
In the meantime, I already wrote better css for maximizing screen size for display while respecting figure aspect ratio. First PR is on its way 😉 

`fig.aspect = 0.5`
![image](https://user-images.githubusercontent.com/34234913/56847401-8aa8fa80-68da-11e9-9df6-cf99284cb5b5.png)
`fig.aspect = 2`
![image](https://user-images.githubusercontent.com/34234913/56847394-7bc24800-68da-11e9-8679-b1decd27708d.png)

**Comment by nstrayer** [comment]
Hey @Felixmil, I got the PR and it's great! I made a few tweaks to it mostly involving [the hook that adds the classes to the plots](https://github.com/nstrayer/tuftesque2/blob/master/docs/index.rmd#L14-L30). Try it out and let me know if you think it's good!

**Comment by nstrayer** [comment]
Adding a gif of the process to use githubs uploading for reference in the readme. 
![Testing Tuftesque2 - Edited (3)](https://user-images.githubusercontent.com/6764693/56853654-78d25200-68f0-11e9-9838-f2a7de5ceb31.gif)
