### ISSUE TITLE
Should hooks be outside of .Rmd ?

### ISSUE THREAD

**Issue by Felixmil** [nstrayer/tuftesque2#9]
As regular report writer, I spend most of the time working and reading directly the .Rmd file rather than the output .

This is why I think it is important that the writer always have a clear view and can focus on the **content.** After all, this why I use themes: if it's practical, sexy and appropriate, I'd use it vanilla and am able to focus fully on R code and chunks options.

As The hooks at the beginning of the .Rmd files are :
1. Not _directly_  usefull to the writer,
2. Necessary for this beautiful theme to work properly (thus, should remain untouched)

Wouldn't it be better to 'hide' it from the user and secure it somewhere else ? Is it possible ? If yes, where ?

**Comment by nstrayer** [comment]
Yes definitely. The only reason they are in the top right now is because I was too lazy to figure out how to bundle them into the actual theme function. I'd imagine it's as simple as passing an argument to the [`rmarkdown::html_document()` function](https://github.com/nstrayer/tuftesque2/blob/master/R/tuftesque.R#L13).

**Comment by Felixmil** [comment]
I didn't find any argument in rmarkdown::html_document() as you mention.

However, I was able to move the first chunk in a `hooks.R` file and replace the first chunk by: 

```
```{r, code=readLines(paste(system.file(package = 'tuftesque2'),'/hooks.R', sep='')), echo=F}```
```
As I don't know how to add an a source file during package compilation, I added the file manually in the package directory 🙈. A function or something like `code=readLines(tuftesque2::hooks))` would be better but I have no idea how to do it.

I realize this is not very good as there would still be a 'setup chunk' in the Rmd file 😐

**Comment by nstrayer** [comment]
https://github.com/nstrayer/tuftesque2/pull/10 In this PR I reformatted the `tuftesque2::tuftesque()` function so the chunk hooks are defined internally in the function.
